sudo: false
language: rust

# Dependencies of kcov, used by coverage
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

rust:
- nightly
- beta
- stable

cache:
  directories:
  - "$HOME/.cargo"

before_script:
- |
  cargo install cargo-travis &&
  export PATH=$HOME/.cargo/bin:$PATH

script:
- |
  cargo build &&
  cargo test &&
  cargo doc

after_success:
- cargo coveralls

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - secure: utujF5pCSGT15tGNhKLNHcRjgokbgC6dt/aMzdYD5riglPxFi8r8iTnJBvgLs1f0UFepZxoZDS2O1QOXvzrEubpUOSBs73x4CtI0rdbq7ERSI5yxQH5sFemo2yTKGQjJIsxl/TB+z+iHDAokwzrgqZUutEWnXc6VquUfif5jnbLwcXr6m9S6HF1tOv0cVR+1cLCwU8NTjefuKPiJwd5gKZf6eb+XOVQVK1RNum+E7/rsRSMAA7sWBSqxUpjA2KkWiGZyBlwAJ1k6Xgw3WrqIhiVpnfmI1J6Ows2cDoVWoPxD52wYBguMHRihbDyxuDv9GLaIV0B1DAqbQHraHjl4ITb/1ynHzkMxP+lrITQeumSb+ty6Bm+8ReL5MTMYHV+OCBJxgYdo96wxiT9f3GPcMASInGMdypSFVLZN8l6tjZch2QkN1Pp8oISYAJVuoLGb9ro2SjB28n7tNnBOANoPor8obrybm4mFWh89HBbkomV3fDMKfr4mN7ySYwHEf75/spzXVuylFGCxiom2bX2rf/i9P0EuPFEcGJenXZcwElD+55Imo4+vbJhodLqyyOpg8mXA1Jqb5zyJP3HaJUOByMLyk5YtGLBM95XQHSJ8NRThXCaMaRDiOqggkn6qdGL+6okoiuxmp6/VQZXNquBH+pb1tqOv7VQo20KIHZgbH/c=
