[package]
name = "rgoap"
version = "0.1.0"
authors = ["Samuel Loretan <tynril@gmail.com>"]
license = "MIT"
description = "Goal-Oriented Action-Planning"
repository = "https://github.com/tynril/rgoap"
documentation = "https://tynril.github.io/rgoap"
keywords = ["goap", "ai", "action-planning"]
readme = "README.md"

[dependencies]
serde = "0.9"
serde_derive = "0.9"
pathfinding = "0.1"

[dev-dependencies]
serde_json = "0.9"
